from .action import Action
import os
import json
import time
from . import utils
from .logger import logger
from filelock import FileLock, Timeout


class CacheAction(Action):
    """
    ####################################################################################################################
    Cache Action
    ####################################################################################################################
    Currently, the following actions are supported for Cache:
    1. find/search
    2. show
    3. list
    4. remove(rm)
    5. prune
    6. mark-tmp

    """

    def __init__(self, parent=None):
        # super().__init__(parent)
        self.__dict__.update(vars(parent))
        self.parent = parent

    def search(self, i):
        """
    ####################################################################################################################
    Target: Cache
    Action: Find (Alias: Search)
    ####################################################################################################################

    The `find` (or `search`) action retrieves the path of cache generated by a particular script.

    Syntax:

    mlc find cache --tags=<list_of_tag_used_to_run_the_particular_script>

    Example Command:

    mlc find cache --tags=get,dataset,igbh

        """
        i['target_name'] = "cache"
        # logger.debug(f"Searching for cache with input: {i}")
        r = self.parent.search(i)
        if r['return'] > 0:
            return r
        cleaned_list = []

        for item in r['list']:
            item_meta = item.meta
            '''#handled in script automation now
            dep = item_meta.get('dependent_cached_path')
            if dep and not os.path.exists(dep):
                continue  # skip item

            deps = item_meta.get('dependent_cached_paths', '').split(',')
            if any(d and not os.path.exists(d) for d in deps):
                continue  # skip item
            '''

            expiration_time = item_meta.get('cache_expiration')
            if expiration_time is not None and expiration_time < time.time():
                continue  # skip expired item

            cleaned_list.append(item)

        r['list'] = cleaned_list

        return r

    find = search

    def rm(self, i):
        """
    ####################################################################################################################
    Target: Cache
    Action: Remove(rm)
    ####################################################################################################################

    The `rm` action removes one or more caches generated while running scripts through MLCFlow.

    Syntax:

    mlc rm cache --tags=<list_of_tag_used_to_run_the_particular_script>

    Options:
        1. `-f`: Force removes caches without confirmation. Without `-f`, the user will be prompted for confirmation before deletion.

    To remove all generated caches, use:

    mlc rm cache

    Example Command:

    mlc rm cache --tags=get,dataset,igbh

        """
        i['target_name'] = "cache"
        # logger.debug(f"Removing cache with input: {i}")
        return self.parent.rm(i)

    def mark_tmp(self, i):
        """
    ####################################################################################################################
    Target: Cache
    Action: Mark Tmp (mark-tmp)
    ####################################################################################################################

    The `mark-tmp` action marks one or more cache entries as `tmp` without removing the cache contents.

    Syntax:

    mlc mark-tmp cache --tags=<list_of_tags_used_to_run_the_particular_script>

    Example Command:

    mlc mark-tmp cache --tags=get,dataset,igbh

        """
        i['target_name'] = "cache"
        res = self.search(i)
        if res['return'] > 0:
            return res

        if len(res['list']) == 0:
            logger.warning(f"No cache found for {i}")
            return {'return': 0, "warnings": [
                {"code": "EMPTY_TARGET", "description": f"No cache found for {i}"}]}

        updated_count = 0

        for item in res['list']:
            meta_yaml_path = os.path.join(item.path, "meta.yaml")
            meta_json_path = os.path.join(item.path, "meta.json")
            lock_file = os.path.join(item.path, ".lock")
            tag_added = False

            try:
                with FileLock(lock_file, timeout=60):
                    # Re-read meta from disk inside the lock to avoid stale reads
                    # from the earlier self.search() call.
                    if os.path.exists(meta_yaml_path):
                        current_meta = utils.read_yaml(meta_yaml_path) or {}
                        use_yaml = True
                    elif os.path.exists(meta_json_path):
                        current_meta = utils.read_json(meta_json_path) or {}
                        use_yaml = False
                    else:
                        logger.warning(
                            f"No meta file found for {item.path}, skipping")
                        continue

                    tags = current_meta.get("tags", [])
                    if 'tmp' in tags:
                        continue

                    tags.append('tmp')
                    current_meta["tags"] = tags

                    if use_yaml:
                        save_result = utils.save_yaml(
                            meta_yaml_path, meta=current_meta)
                    else:
                        save_result = utils.save_json(
                            meta_json_path, meta=current_meta)

                    if save_result['return'] > 0:
                        return save_result

                    item.meta = current_meta
                    tag_added = True
            except Timeout:
                return {
                    'return': 1,
                    'error': f"Could not acquire lock for {item.path} within 60 seconds"
                }

            if tag_added:
                self.get_index().update(item.meta, "cache", item.path, item.repo)
                updated_count += 1

        logger.info(f"Marked {updated_count} cache item(s) as tmp")

        return {
            'return': 0,
            'message': f"Marked {updated_count} cache item(s) as tmp",
            'list': res['list']
        }

    def show(self, run_args):
        """
    ####################################################################################################################
    Target: Cache
    Action: Show
    ####################################################################################################################

    Retrieves the path and metadata of caches generated while running scripts through MLCFlow.

    Syntax:

    mlc show cache --tags=<list_of_tags_used_while_running_script>

    Example Command:

    mlc show cache --tags=get,dataset,igbh

    Note:
    - The `find` action is a subset of `show`. It retrieves only the path of the searched cache.

        """
        self.action_type = "cache"
        res = self.search(run_args)
        if res['return'] > 0:
            return res

        logger.info(f"Showing cache with tags: {run_args.get('tags')}")
        cached_meta_keys_to_show = [
            "uid",
            "tags",
            "dependent_cached_path",
            "associated_script_item"]
        cached_state_keys_to_show = ["new_env", "new_state", "version"]
        for item in res['list']:
            print(f"""Location: {item.path}:
Cache Meta:""")
            for key in cached_meta_keys_to_show:
                if key in item.meta:
                    print(f"""    {key}: {item.meta[key]}""")
            print("""Cached State:""")
            cached_state_meta_file = os.path.join(
                item.path, "mlc-cached-state.json")
            if not os.path.exists(cached_state_meta_file):
                continue
            try:
                # Load and parse the JSON file containing the cached state
                with open(cached_state_meta_file, 'r') as file:
                    meta = json.load(file)
                    for key in cached_state_keys_to_show:
                        if key in meta:
                            print(f"""    {key}:""", end="")
                            if meta[key] and isinstance(meta[key], dict):
                                print("")
                                utils.printd(
                                    meta[key], yaml=False, sort_keys=True, begin_spaces=8)
                            else:
                                print(f""" {meta[key]}""")
            except json.JSONDecodeError as e:
                logger.error(f"Error decoding JSON: {e}")
            print("......................................................")
            print("")

        return {'return': 0}

    def prune(self, args):
        """
    ################################################################################
    Target: Cache
    Action: Prune
    ################################################################################

    Prune expired cached items. Supports optional filtering by tags.

    Syntax:

    mlc prune cache
    mlc prune cache --tags=<tags>

    Example Commands:

    mlc prune cache
    mlc prune cache --tags=get,dataset

        """
        self.action_type = "cache"
        run_args = {"fetch_all": True}
        tags = args.get('tags')
        if tags:
            run_args['tags'] = tags

        # Use parent.search to bypass expiration filtering in self.search,
        # so we can find the expired entries ourselves
        run_args['target_name'] = "cache"
        res = self.parent.search(run_args)
        if res['return'] > 0:
            return res

        expired = []
        for item in res['list']:
            expiration_time = item.meta.get('cache_expiration')
            if expiration_time is not None and expiration_time < time.time():
                expired.append(item)

        if not expired:
            logger.info("No expired cache entries found.")
            return {'return': 0}

        logger.info(f"Found {len(expired)} expired cache entries:")
        for item in expired:
            item_tags = ','.join(item.meta.get('tags', []))
            logger.info(
                f"  {item.meta.get('uid', '?')} [{item_tags}] -> {item.path}")

        removed = 0
        for item in expired:
            uid = item.meta.get('uid')
            if uid:
                ii = {'f': True, 'item': uid, 'target_name': 'cache'}
                r = self.rm(ii)
                if r.get('return', 0) == 0:
                    removed += 1

        logger.info(f"Pruned {removed} expired cache entries.")
        return {'return': 0, 'pruned': removed}

    def list(self, args):
        """
    ####################################################################################################################
    Target: Cache
    Action: List
    ####################################################################################################################

    Lists all cached items along with their paths.

    Example Command:

    mlc list cache

        """
        self.action_type = "cache"
        # to fetch the details of all the caches generated
        run_args = {"fetch_all": True}

        res = self.search(run_args)
        if res['return'] > 0:
            return res

        logger.info(f"Listing all the caches and their paths")
        print("......................................................")
        for item in res['list']:
            print(
                f"tags: {item.meta['tags'] if item.meta.get('tags') else 'None'}")
            print(f"Location: {item.path}")
            print("......................................................")

        return {'return': 0}
